version: '3'
services:
  message-service:
    build:
      context: .
      dockerfile: docker/Dockerfile-message-service
    depends_on:
      - rabbitmq
    ports:
      - "5000:5000"
  rabbitmq:
    image: bitnami/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
