version: '3.8'
services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # RabbitMQ Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  database-service:
    build: ./src/database-service
    container_name: database-service
    ports:
      - "27017:27017"  # MongoDB port
    volumes:
      - ./src/database-service/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  message-service:
    build: ./src/message-service
    container_name: message-service
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - database-service
    environment:
      - RABBITMQ_HOST=rabbitmq  # RabbitMQ hostname for message distribution

  user-service:
    build: ./src/user-service
    container_name: user-service
    ports:
      - "5001:5000"
    depends_on:
      - rabbitmq
      - database-service
