apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
  namespace: chat-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: message-service
        image: your-image-name
        ports:
          - containerPort: 5000
