apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service
  namespace: chat-system
spec:
  replicas: 1  # MongoDB replica set will handle scaling
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
    spec:
      containers:
        - name: database-service
          image: mongo:latest  # Official MongoDB image
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: init-scripts
              readOnly: true
      volumes:
        - name: init-scripts
          configMap:
            name: init-mongo-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: chat-system
spec:
  selector:
    app: database-service
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
