apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service
  namespace: chat-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
    spec:
      containers:
      - name: database-service
        image: database-service  # Replace with the actual Docker image name
        ports:
          - containerPort: 27017  # Default MongoDB port (adjust if necessary)
        env:
          - name: RABBITMQ_HOST
            value: "rabbitmq"  # Connect to RabbitMQ service
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: chat-system
spec:
  selector:
    app: database-service
  ports:
    - protocol: TCP
      port: 27017  # Default MongoDB port
      targetPort: 27017
  type: ClusterIP
