apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: chat-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest  # Replace with your actual image
          ports:
            - containerPort: 5000
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: MONGO_URI
              value: "mongodb://database-service:27017/"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: chat-system
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
